### PR TITLE
disable PR check and allow user to label PR

### PR DESCRIPTION
**Pull request by lanking520**
Add PR option to add labels @nswamy.

### CODE REVIEW

**Comment by nswamy** [comment]
LGTM. @marcoabreu once you merge, can you make sure that the new code is deployed to Lambda?

**Comment by marcoabreu** [comment]
Sorry, I'm currently swamped with high priority tasks and I don't have time to review your task or assist with inqueries.

**Comment by larroy** [comment]
I'm fine with merging this small change, but can we please refactor that inner function? it's difficult to maintain.

**Comment by lanking520** [comment]
@larroy Thanks for your reply Pedro. I will prepare another PR to address these concerns

**Pull request merged**
